name: Build Picviewer CE+ Dist

on:
  push:
    branches:
      - master
    paths:
      - 'Picviewer CE*/Picviewer CE*.user.js'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace require paths, add timestamp, and create dist file
        run: |
          sed -E \
            -e "s#https://update.greasyfork.org/scripts/6158/([0-9]+)/GM_config%20CN.js#https://hoothin.github.io/UserScripts/Picviewer%20CE%2B/GM_config%20CN.js?v=\1#g" \
            -e "s#https://update.greasyfork.org/scripts/438080/([0-9]+)/pvcep_rules.js#https://hoothin.github.io/UserScripts/Picviewer%20CE%2B/pvcep_rules.js?v=\1#g" \
            -e "s#https://update.greasyfork.org/scripts/440698/([0-9]+)/pvcep_lang.js#https://hoothin.github.io/UserScripts/Picviewer%20CE%2B/pvcep_lang.js?v=\1#g" \
            "Picviewer CE+/Picviewer CE+.user.js" > "Picviewer CE+/dist.user.js"

      - name: Commit and push dist.user.js
        run: |
          git config --local user.email "rixixi@gmail.com"
          git config --local user.name "hoothin-update"
          git add "Picviewer CE+/dist.user.js"
          git commit -m "chore(Picviewer CE+): Auto-generate dist.user.js"
          git push https://${{ secrets.ACTION_SECRET }}@github.com/${{ github.repository }}
